---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
- name: zabbix
  box: debian/buster64
  memory: 8192
  cpus: 2
  interfaces:
  - virtualbox__intnet: zabbixnet
    network_name: private_network
    ip: 192.168.0.1
  provider_raw_config_args:
  - "customize ['createhd', '--filename', '$MOLECULE_EPHEMERAL_DIRECTORY/zabbix.vdi', '--size', 96 * 1024]"
  - "customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--device', 0, '--port', 1, '--type', 'hdd', '--medium', '$MOLECULE_EPHEMERAL_DIRECTORY/zabbix.vdi']"
  instance_raw_config_args:
  - "vm.network 'forwarded_port', guest: 8080, host: 8080"
  groups:
    - tp.zabbix_configure
  provision: True
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .
provisioner:
  name: ansible
  env:
    # yes, both, depending on wether you're running ansible <=2.9 or >=2.10
    ANSIBLE_COLLECTIONS_PATH: ../../collections/
    ANSIBLE_COLLECTIONS_PATHS: ../../collections/
  inventory:
    links:
      group_vars: ../../../../environments/molecule/group_vars/
      hosts: ../../../../environments/molecule/hosts.yml
  config_options:
    defaults:
      vault_identity_list: ../../test/fixtures/vault_password_file
      inventory_ignore_extensions: ~, .orig, .bak, .ini, .cfg, .retry, .pyc, .pyo, .cache
    ssh_connection:
      pipelining: True
      control_path: /tmp/ansible-ssh-%%h-%%p-%%r
verifier:
  name: ansible
