---
- name: Wait for frontend at {{ tp_zabbix_check_frontend_url }} to come up
  ansible.builtin.uri:
    url: "{{ tp_zabbix_check_frontend_url }}"
    status_code: 200
    timeout: "{{ tp_zabbix_check_api_timeout }}"
  delegate_to: localhost
  register: monitoring_frontend_available
  until: monitoring_frontend_available.status == 200
  retries: 3
  delay: 2
  failed_when: False
  run_once: True
  check_mode: no

- name: Create or update monitoring template
  ansible.builtin.include_tasks: monitoring.yml
  when:
    - monitoring_frontend_available.status is defined  # contrary to the docs, uri does NOT always return a status.
    - monitoring_frontend_available.status == 200
