---
- name: Create new database {{ dbmonitoring_db_name }}
  postgresql_db:
    name: "{{ dbmonitoring_db_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    tablespace: pg_default
    conn_limit: '-1'
    template: template0
    login_unix_socket: "/srv/{{ dbmonitoring_service_name }}"
  become: True

- name: Create user "{{ dbmonitoring_db_username }}""
  include_role:
    name: tp.db_user
  vars:
    tp_db_user_host: "{{ ansible_hostname[:-2] }}"
    tp_db_user_username: "{{ dbmonitoring_db_username }}"
    tp_db_user_password: "{{ dbmonitoring_db_password }}"

- name: Create schema "{{ dbmonitoring_db_name }}""
  postgresql_schema:
    db: "{{ dbmonitoring_db_name }}"
    name: "{{ dbmonitoring_db_name }}"
    owner: "{{ dbmonitoring_service_name }}"
    login_unix_socket: "/srv/{{ dbmonitoring_service_name }}"
  become: True

- name: GRANT ALL PRIVILEGES ON SCHEMA {{ dbmonitoring_db_name }} TO {{ dbmonitoring_db_username }}
  postgresql_privs:
    db: "{{ dbmonitoring_db_name }}"
    privs: ALL
    type: schema
    objs: "{{ dbmonitoring_db_name }}"
    role: "{{ dbmonitoring_db_username }}"
    login_unix_socket: "/srv/{{ dbmonitoring_service_name }}"
  become: True
