---
- name: Call API to see if zabbix-item already exists
  ansible.builtin.uri:
    url: "{{ tp_zabbix_item_factory_automation_url }}/api_jsonrpc.php"
    method: POST
    body_format: json
    headers:
      Content-Type: application/json-rpc
    body:
      jsonrpc: '2.0'
      method: item.get
      auth: "{{ tp_zabbix_item_factory_api_login.json.result }}"
      params:
        output: extend
        selectPreprocessing: extend
        hostids: "{{ tp_zabbix_item_factory_dummy_host_info.hosts[0].hostid }}"
        search:
          name: "{{ tp_zabbix_item_factory_item.name }}"
      id: 3
    timeout: "{{ tp_zabbix_item_factory_api_timeout }}"
  delegate_to: localhost
  register: tp_zabbix_item_factory_api_call_returns
  check_mode: False

- name: Show existing item
  # This is a helper for development:
  # Click your item in the frontend, then run the role with "--check -vv" and copy-paste this block to your yaml.
  ansible.builtin.debug:
    msg: "{{ tp_zabbix_item_factory_api_call_returns.json.result | to_nice_yaml(indent=2) }}"
    verbosity: 2
  check_mode: False

- name: Call API to create items when it does not
  ansible.builtin.uri:
    url: "{{ tp_zabbix_item_factory_automation_url }}/api_jsonrpc.php"
    method: POST
    body_format: json
    headers:
      Content-Type: application/json-rpc
    body:
      jsonrpc: '2.0'
      method: item.create
      auth: "{{ tp_zabbix_item_factory_api_login.json.result }}"
      params: "{{ tp_zabbix_item_factory_item_defaults | combine(tp_zabbix_item_factory_item) }}"
      id: 4
    timeout: "{{ tp_zabbix_item_factory_api_timeout }}"
  delegate_to: localhost
  when:
    - not (tp_zabbix_item_factory_api_call_returns.json.result | length)

- name: Call API to update the zabbix-item otherwise
  ansible.builtin.uri:
    url: "{{ tp_zabbix_item_factory_automation_url }}/api_jsonrpc.php"
    method: POST
    body_format: json
    headers:
      Content-Type: application/json-rpc
    body:
      jsonrpc: '2.0'
      method: item.update
      auth: "{{ tp_zabbix_item_factory_api_login.json.result }}"
      params: >
        {{
          tp_zabbix_item_factory_item_defaults
          | combine(tp_zabbix_item_factory_item)
          | combine({ 'itemid': tp_zabbix_item_factory_api_call_returns.json.result[0].itemid })
        }}
      id: 5
    timeout: "{{ tp_zabbix_item_factory_api_timeout }}"
  delegate_to: localhost
  when:
    - (tp_zabbix_item_factory_api_call_returns.json.result | length)
    - tp_zabbix_item_factory_api_call_returns.json.result[0].name | default('') == tp_zabbix_item_factory_item.name
